%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\tomek\OneDrive\Dokumenty\FIR\output.dat
%
% Auto-generated by MATLAB on 16-Jun-2020 16:59:12

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 1);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = "b110";
opts.VariableTypes = "double";

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
output = readtable("<Ścieżka do folderu z plikami>\output.dat", opts);


%% Clear temporary variables
clear opts